paths:
  /api/products/:
    get:
      summary: Obtiene todos los productos
      tags:
        - Products
      responses:
        "200":
          description: Los productos se listaron correctamente.
        "500":
          description: Error internos del servirod al obtener los productos.